### ISSUE TITLE
Add equivalence of finite sequences?

### ISSUE THREAD

**Issue by mpilgrem** [ombocomp/type-iso#3]
I found this package while looking to convert between `Data.Sequence.Seq a` from package `containers` and `Data.Vector.Generic.Vector v a => v a` from package `vector`.

Would those types be candidates for further instances? If so, I can make a pull request.

**Comment by jtapolczai** [comment]
Hi!
Sorry, I've been snowed in with work.

I think those two ought to be isomorphic, so feel free to make a pull-request!
